openapi: 3.0.0
servers:
  - description: Sandbox server
    url: '/api/v1'
info:
  version: "1.0.0"
  title: API documentation
tags:
  - name: content
    description: Access to your personal content items
  - name: user
    description: Access to user personal information
  - name: connector
    description: Access to available connectors
paths:
  /user/setting:
    $ref: ./src/paths/user/setting.yaml
  /user/logout:
    $ref: ./src/paths/user/logout.yaml
  /item:
    $ref: ./src/paths/content/item.yaml
  /item/{hash}:
    $ref: ./src/paths/content/item-by-hash.yaml
  /item/{hash}/visibility:
    $ref: ./src/paths/content/item-visibility.yaml
  /connector:
    $ref: ./src/paths/connector/index.yaml
  /connector/{name}:
    $ref: ./src/paths/connector/connector-by-name.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer