openapi: 3.0.0
servers:
  - description: Sandbox server
    url: '/api/v1'
info:
  version: "1.0.0"
  title: API documentation
tags:
  - name: content
    description: Access to your personal content items
  - name: user
    description: Access to user personal information
  - name: connector
    description: Access to available connectors
paths:
  /user/setting:
    $ref: ./src/paths/user/setting.yaml
  /user/redirect-session/{sessionId}:
    $ref: ./src/paths/user/redirect-session-by-sessionid.yaml
  /user/redirect-session:
    $ref: ./src/paths/user/redirect-session.yaml
  /user/logout:
    $ref: ./src/paths/user/logout.yaml
  /item:
    $ref: ./src/paths/content/item.yaml
  /item/{connectorId}:
    $ref: ./src/paths/content/create.yaml
  /item/{hash}:
    $ref: ./src/paths/content/item-by-hash.yaml
  /connector:
    $ref: ./src/paths/connector/index.yaml
  /preview:
    $ref: src/paths/content/preview.yaml
  /connector/{name}:
    $ref: ./src/paths/connector/connector-by-name.yaml
  /stat/category:
    $ref: ./src/paths/stat/stat-category.yaml
  /stat/connector:
    $ref: ./src/paths/stat/stat-connector.yaml
  /stat/connector/{name}:
    $ref: ./src/paths/stat/stat-connector-by-name.yaml
  /stat/improvement:
    $ref: ./src/paths/stat/improvement.yaml
  /stat/improvement/{name}:
    $ref: ./src/paths/stat/improvement-by-name.yaml
  /auth/postback-google:
    $ref: ./src/paths/auth/postback-google.yaml
  /auth/postback-apple:
    $ref: ./src/paths/auth/postback-apple.yaml
  /auth/signup:
    $ref: src/paths/auth/signup.yaml
  /auth/login:
    $ref: src/paths/auth/login.yaml
  /auth/reset-password:
    $ref: src/paths/auth/reset-password.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer