type: object
properties:
  username:
    type: string
    description: User name
    example: nickname
  email:
    type: string
    description: User email
    example: nickname@example.com
  language:
    type: string
    description: ISO 2 language code
    example: en