type: object
properties:
  username:
    type: string
    description: User name
    example: nickname
  avatar:
    type: string
    description: User avatar url
    example: https://cdn.teleboard.io/images/23/yLUMyHkUQfrD.jpg"
  email:
    type: string
    description: User email
    example: nickname@example.com
  refCode:
    type: string
    description: User referal code
    example: 5m411
  refUrl:
    type: string
    description: User referal url link
    example: https://teleboard.io/app?r=5m411"
  languages:
    type: array
    description: Available languages ​​for service localization
    items:
      type: object
      properties:
        code:
          type: string
          description: ISO 2 language code
          example: en
        title:
          type: string
          description: Language name
          example: English
        active:
          type: boolean
          description: Indicate which language is active for the current user
          example: true
