type: object
properties:
  username:
    type: string
    description: User name
    example: nickname
  email:
    type: string
    description: User email
    example: nickname@example.com
  languages:
    type: array
    description: Available languages ​​for service localization
    items:
      type: object
      properties:
        code:
          type: string
          description: ISO 2 language code
          example: en
        active:
          type: boolean
          description: Indicate which language is active for the current user
          example: true
